### ISSUE TITLE
Avoid polluting the page cache when backing up files

### ISSUE THREAD

**Issue by jasobrown** [Netflix/Priam#316]
Current implementation naively reads files to be backed up off disk, which will put those blocks into the OS page cache. If you have a lot of memory on the machine, there is a negligible cost (assuming you can even see it). However, on machines with less memory, pulling all the cold sttables through the page cache will evict the hot blocks quicly, and thus you can run into performance degradation, with lots of competing IO and page cache thrashing.

It should be possible to avoid reading the backup files through the page cache - I think it's just an fadvise flag. However, I don't believe those options are exposed in the JDk, and thus might need to use jna to set it. Cassandra itself already does a lot of these kind of techniques, so it should be reasonably straight-forward to add it into priam.

**Comment by timiblossom** [comment]
@danchia since you are still using Priam, lets keep this open if you have the patch :).

**Comment by danchia** [comment]
It turns out we ended up moving to bigger machines for other reasons, so this didn't affect us anymore.
