### ISSUE TITLE
priam-web.war won't deploy in tomcat 7

### ISSUE THREAD

**Issue by mcacker** [Netflix/Priam#335]
May 9, 2014 9:46:18 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /opt/apache-tomcat-7.0.34/webapps/priam-web.war
May 9, 2014 9:46:19 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(/tomcat/webapps/priam-web/WEB-INF/lib/servlet-api-2.5-20081211.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class
May 9, 2014 9:46:24 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
May 9, 2014 9:46:24 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/priam-web] startup failed due to previous errors

I've confirmed that the offending jar, javax.servlet:servlet-api:2.5, IS included in the war file.  I've also seen that it should be excluded as your build.gradle file has

           provided "javax.servlet:servlet-api:2.5"

not sure why it's getting included, but it won't run in tomcat 7.

**Comment by tulumvinh** [comment]
Hi,

To see how Gradle resolves the dependencies, please run gradle's dependencyInsight on the aforementioned resource.

Thanks

**Comment by rspieldenner** [comment]
If another dependency has put it on compile or runtime it might go into the
war.
