### ISSUE TITLE
Priam Full Restore is not working: Exception encountered during startup: Unable to contact any seeds!

### ISSUE THREAD

**Issue by droyzenberg** [Netflix/Priam#338]
I have 3 nodes cluster 1.2  I noticed that the full recovery is not working properly.
Here is my scenario:
1) Make a backup 
curl -s http://localhost:8080/Priam/REST/v1/backup/do_snapshot
2) Take a note of the snap ID: 201405201409

3) Stop C* on all 3 nodes
4) Remove data on each node
sudo rm /mnt/data/commitlog/*
sudo rm -rf /mnt/data/db/cassandra/*

5) Restore Backup on all nodes
curl -s http://localhost:8080/Priam/REST/v1/backup/restore?daterange=201405201409,201405201409

6) Start C* on each node

I getting following errors in the log:
Exception encountered during startup: Unable to contact any seeds!

http://pastebin.com/Q95Zi8ZH

Please advise,
Thanks!

**Comment by tulumvinh** [comment]
Hi,

This (http://stackoverflow.com/questions/21261098/cassandra-unable-to-contact-seeds-if-using-aws-elastic-ip-address-only-works) might be relevant to your use case.

Let us know if you still encounter issues.

Thanks
