### ISSUE TITLE
Cannot POST to S3 backup bucket in us-west-2

### ISSUE THREAD

**Issue by pdehlke** [Netflix/Priam#341]
priam 1.2.29, running successfully in us-east-1. When I copy my AMI (which is fully baked with all the tomcat/priam/cassandra bits, no post-boot customizations are done) to us-west-2, priam is no longer able to create cassandra backups in S3:

014-05-28 02:32:39.0204 DEBUG DefaultQuartzScheduler_Worker-1 com.amazonaws.request Received error response: Status Code: 301, AWS Service: null, AWS Request ID: 596FB7D4F3E8BA0B, AWS Error Code: PermanentRedirect, AWS Error Message: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint., S3 Extended Request ID: wSJg0H74J/dKeOBTqJBdm6o/AINZJWLHXBoT890pCvFXKaEritb0ms72ITOtLeLrTi37BEtA7XE=

From the logs, it appears to me that priam is inserting a space in the URI it attempts to POST to:

014-05-28 02:32:39.0190 DEBUG DefaultQuartzScheduler_Worker-1 com.amazonaws.request Sending Request: POST https://REDACTED-cassandra-backups
.s3-us-west-2.amazonaws.com /cassandra_backups%2Fus-west-2%2Fcassandra%2F14178431955039102644307275311624381702%2F201405280204%2FSST%2Fsyst
em%2Fschema_keyspaces%2Fsystem-schema_keyspaces-jb-1-Data.db Parameters: (uploads: null, ) Headers: (Authorization: AWS REDACTED:REDACTED, Date: Wed, 28 May 2014 02:32:39 GMT, User-Agent: aws-sdk-java/1.3.27 Linux/3.13.0-24-generic Java_HotSpot(T
M)_64-Bit_Server_VM/24.51-b03, Content-Type: application/x-www-form-urlencoded; charset=utf-8, )

Am I misreading the log?

**Comment by tulumvinh** [comment]
Hi pdehlke,

Base on the original stack trace you provided, AWS complains about the endpoint.  You mentioned that there is a blank in the generated uri, how are you providing the host and bucket name to Priam?

Thanks
