### ISSUE TITLE
Steps for turning a 2.0.8 cluster into multi-region

### ISSUE THREAD

**Issue by ersiko** [Netflix/Priam#370]
Hi

I have a cluster running in a region, and I'm trying to turn it into multi-region, but I haven't found any documentation for that. Is there any?

Meanwhile, checking the available properties in https://github.com/Netflix/Priam/wiki/2.0 I made some changes in simpledb:
- I changed 'priam.multiregion.enable' to 'true'
- I added the new AZs to 'priam.zones.available'.
- Changed priam.endpoint_snitch to 'org.apache.cassandra.locator.Ec2MultiRegionSnitch'

Now, when the servers in the new region start, they call "get_seeds" in the API and get 10.0.x.x private addresses, and obviously they can't connect to those IPs, so cassandra startup log shows "Unable to gossip with any seeds" error.

Checking the security groups in both regions I see Priam has added new rules, but always using the private addresses, not the public ones.

Also I've tried starting from scratch, with no data in the servers, just the info in simpledb (after changing multiregion, endpoint_snitch and the new AZs),but I get the same error.

What am I missing? How can I make Priam use public IP addresses for inter-region communication insead of private IPs?

I'm using version 2.0.8 for Cassandra and Priam, com.netflix.priam.cassandra.extensions.NFSeedProvider and org.apache.cassandra.dht.RandomPartitioner. For the rest I'm using mostly the defaults.

Any hint?

Thanks in advance,
Tomàs

**Comment by fluzz** [comment]
did you ever get this working?

**Comment by timiblossom** [comment]
You need to update Priam's SimpleDb or whatever you are using with Public IP before launching a new region.
