### ISSUE TITLE
Doubling cluster procedure?

### ISSUE THREAD

**Issue by droyzenberg** [Netflix/Priam#377]
Hi there, 
It seems that the wiki page for doubling cluster is empty.
Could you please provide a steps how to do it?

Also, is it possible to reduce cluster size with Priam?

Thanks!

**Comment by timiblossom** [comment]
Here are the steps:

1. Run Priam's doublling REST API and this will populate entries onto your database.
2. Bring up a new instance one by one and each of them will own a new row in Priam's database. Wait and verify each of those new nodes to make sure they are fully joined the ring before bringing in a new instance.
