### ISSUE TITLE
priam-web won't start due to binding errors on TokenRetrievers

### ISSUE THREAD

**Issue by scottmcmaster** [Netflix/Priam#424]
On the 2.x branch...I get 24 binding errors trying to start the web app, all related to these non-existent bindings:

        bind(IDeadTokenRetriever.class).to(DeadTokenRetriever.class);
        bind(IPreGeneratedTokenRetriever.class).to(PreGeneratedTokenRetriever.class);
        bind(INewTokenRetriever.class).to(NewTokenRetriever.class);

Is this possibly a merge issue at 2d812fefb8bc6eb740aec1d9a40b9521805cadf8?

**Comment by tulumvinh** [comment]
Hi Scott,

The implementations (DeadTokenRetriever, PreGeneratedTokenRetriever, and NewTokenRetriever) are located in https://github.com/Netflix/Priam/tree/2.x/priam/src/main/java/com/netflix/priam/identity/token

If OSS Priam was built successfully, these implementations should exist in your Priam-*.jar file.   If your built was successful, please ensure that the implementation class is in the jar.

**Comment by scottmcmaster** [comment]
Sorry, re-reading my description, I wasn't super-clear. They're not bound in PriamGuiceModule: https://github.com/Netflix/Priam/blob/2.x/priam/src/main/java/com/netflix/priam/defaultimpl/PriamGuiceModule.java

If they really should be, then I can send you a pull request.

**Comment by tulumvinh** [comment]
Scott, you are absolutely right, please submit a pull request and I will approve it.

Thanks

**Comment by sihaizhida** [comment]
Could anyone tell me how to run the Priam with Cassandra?After importing the project into the Eclipse,I've no idea how to run it, I'new about it.

**Comment by tulumvinh** [comment]
Hi Sihaizhida,

Priam is a sidecar to Cassandra.  Specifically, for a node, there will two processes, Priam and Cassandra.  If you look at the documentation, it will state the purpose/features of Priam.  Basically, Priam is the manager of a Cassandra process and as such, it will start Cassandra.  Priam is usually run within a web container (Tomcat) while Cassandra is a stand-alone Java process.

Regards

**Comment by sihaizhida** [comment]
Hi tulumvinh, 
Thank you for your kindness to answering my question. I just don't understand how to run the project, can it operate under windows or other linux environment such as ubuntu now? Do you have any document that describes the setup procedures in detail?
