### ISSUE TITLE
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.7']

### ISSUE THREAD

**Issue by Pratik2290** [Netflix/Priam#426]
I am trying to install Priam on Mac machine which has Java with version  "1.7.0_79" installed on it.
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

I am getting below exception when I try to build the project.

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.7']
> repository not found: /Users/Pratik_Bajaj/Documents/Priam/Priam-master

Below is the stacktrace of above exception:

12:02:35.952 [ERROR] [org.gradle.BuildExceptionReporter]
12:02:35.954 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
12:02:35.954 [ERROR] [org.gradle.BuildExceptionReporter]
12:02:35.954 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
12:02:35.954 [ERROR] [org.gradle.BuildExceptionReporter] Build file '/Users/Pratik_Bajaj/Documents/Priam/Priam-master/build.gradle' line: 2
12:02:35.955 [ERROR] [org.gradle.BuildExceptionReporter]
12:02:35.955 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
12:02:35.955 [ERROR] [org.gradle.BuildExceptionReporter] An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.7']
12:02:35.955 [ERROR] [org.gradle.BuildExceptionReporter] > repository not found: /Users/Pratik_Bajaj/Documents/Priam/Priam-master
12:02:35.955 [ERROR] [org.gradle.BuildExceptionReporter]
12:02:35.956 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
12:02:35.956 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'nebula.netflixoss', version: '2.2.7']
12:02:35.956 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:168)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:124)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:131)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:59)
12:02:35.957 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
12:02:35.958 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
12:02:35.959 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
12:02:35.960 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.Main.doAction(Main.java:33)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
12:02:35.961 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /Users/Pratik_Bajaj/Documents/Priam/Priam-master
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.lib.BaseRepositoryBuilder.build(BaseRepositoryBuilder.java:575)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.Git.open(Git.java:113)
12:02:35.962 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.Git.open(Git.java:97)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.eclipse.jgit.api.Git$open.call(Unknown Source)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.Grgit.open(Grgit.groovy:223)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.Grgit.open(Grgit.groovy)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.ajoberstar.grgit.Grgit$open.call(Unknown Source)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at nebula.plugin.release.ReleasePlugin$_apply_closure2.doCall(ReleasePlugin.groovy:43)
12:02:35.963 [ERROR] [org.gradle.BuildExceptionReporter] 	at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy:42)
12:02:35.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at nebula.plugin.release.ReleasePlugin.apply(ReleasePlugin.groovy)
12:02:35.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
12:02:35.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
12:02:35.964 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.plugins.PluginContainer$apply.call(Unknown Source)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(NetflixOssProjectPlugin.groovy:54)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at nebula.plugin.netflixossproject.NetflixOssProjectPlugin.apply(NetflixOssProjectPlugin.groovy)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
12:02:35.965 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$4.run(DefaultPluginRequestApplicator.java:126)
12:02:35.966 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:156)
12:02:35.966 [ERROR] [org.gradle.BuildExceptionReporter] 	... 36 more
12:02:35.966 [ERROR] [org.gradle.BuildExceptionReporter]
12:02:35.966 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:02:35.966 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
12:02:35.966 [LIFECYCLE] [org.gradle.BuildResultLogger]
12:02:35.967 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 4.392 secs

Also I have this jar present at my local machine.

ls ~/.gradle/caches/modules-2/files-2.1/com.netflix.nebula/gradle-netflixoss-project-plugin/2.2.7/8c6d43ab7c16a6674a2972f48a7e0c7bf69f52d6/gradle-netflixoss-project-plugin-2.2.7.jar

Can someone please look into it and guide me where I got wrong.

**Comment by tulumvinh** [comment]
Hello,

Base on stack trace, it looks like gradle is looking for repo /Users/Pratik_Bajaj/Documents/Priam/Priam-master and is unable to find it.

Regards
