### ISSUE TITLE
Priam is not deleting incremental files.

### ISSUE THREAD

**Issue by sciclon** [Netflix/Priam#431]
Hi guys,

After investigating I realized that Priam is uploading the incremental backups to the S3 buckets and the snapshot as well but I see the files still remains in /backup/ folder.

I know they are hard links but they are not deleted from the backup folder, they are referenced just once (it is not because the file exists in data folder).

My doubt is, should I delete the files on my own? if this is true, should I compared what was uploaded to S3 and then remove the files? 

Additional info:
Cassandra version: 2.0.9 ( I know is a bit older )

Priam log:
08/SST/system/compactions_in_progress/system-compactions_in_progress-jb-4813-Filter.db with chunk size 10485760
2015-10-27 18:37:35.0321 INFO DefaultQuartzScheduler_Worker-5 com.netflix.priam.aws.S3FileSystem Uploading to whatever-development/backup/eu-west-1/whatever/56713727820156410577229101239000783354/201510222039/SST/system/compactions_in_progress/system-compactions_in_progress-jb-3442-Filter.db with chunk size 10485760

Thanks.

**Comment by tulumvinh** [comment]
Hello,

Priam will delete the file on disk (under "backups" for incrementals and "snapshots" for daily backups) if the upload is successful.  Base on your snippet of the log, the upload is in-progress.

Regards

**Comment by sciclon** [comment]
Thanks for the replay,

I can see in the source code, for example the way Priam the "snapshots" in 
priam/src/main/java/com/netflix/priam/backup/SnapshotBackup.java

    private void clearSnapshot(final String snapshotTag) throws Exception                                                                                                                                                                 
     {
         new RetryableCallable<Void>()
         {
             public Void retriableCall() throws Exception
             {
                 JMXNodeTool nodetool = JMXNodeTool.instance(config);
                 nodetool.clearSnapshot(snapshotTag);
                 return null;
             }
         }.call();
     }

I can see how priam uses nodetool to delete the snapshots after uploading them to S3, in the other hand I see the incremental files are uploaded to S3 but not deleted in file:
priam/src/main/java/com/netflix/priam/backup/IncrementalBackup.java

Line 61:
       logger.debug("Scanning for backup in: {}", dataDir.getAbsolutePath());
        for (File keyspaceDir : dataDir.listFiles())
        {
            if (keyspaceDir.isFile())
        			continue;
            for (File columnFamilyDir : keyspaceDir.listFiles())
            {
                File backupDir = new File(columnFamilyDir, "backups");
                if (!isValidBackupDir(keyspaceDir, columnFamilyDir, backupDir))
                    continue;
                upload(backupDir, BackupFileType.SST);
            }
        }
     		
        	if(incrementalRemotePaths.size() > 0)
        	{
        		notifyObservers();
        	}

    }

That is my confusion, I cant find in the source code where Priam is deleting the incremental backups after uploading them.

Thanks again

**Comment by tulumvinh** [comment]
Hello,

Within IncrementalBackup.java invokes AbstractBackup.upload().  Within AbstractBackup.upload(), if upload is successful, it executes "file.delete()".

Regards

**Comment by sciclon** [comment]
Thanks! I will check as in the log I always see the "uploading to" and the files are successfully uploaded in the S3 bucket, I will let you know when I find what is what I am missing

**Comment by sciclon** [comment]
Hey,

The code is fine, I see the method "delete" comes from the class http://www.tutorialspoint.com/java/io/file_delete.htm

As we know it is very common that Cassandra and Priam run with different UID, so it would be great to catch and inform if the files can't be deleted (i.e: file permissions) so I sent a PR to add a log when it fails as the function is not checking the return value of delete.

File: priam/src/main/java/com/netflix/priam/backup/AbstractBackup.java


Thanks!

**Comment by tulumvinh** [comment]
Hi, I'll take a look at the PR.  Regards
