### ISSUE TITLE
Can you please provide documentation to deploy priam application

### ISSUE THREAD

**Issue by me-snail** [Netflix/Priam#435]
Hi ,

 i am not very familiar with gradle.
 i have created war using "gradlew war" command.
 tried to deploy in tomcat 7.
 But i am not able to access rest-api.
 Can anybody please help with application deployment and also with respective properties settings.

**Comment by sciclon** [comment]
Hey @me-snail,

What is the error you are getting? did you copied the Priam.war and priam-cass-extensions.jar files? DId you follow the steps in the setup link?
https://github.com/Netflix/Priam/wiki/Setup
