### ISSUE TITLE
failing to write cassandra.yaml

### ISSUE THREAD

**Issue by pankajbhanu** [Netflix/Priam#436]
Hi
I am using priam-2.x branch with cassandra 2.0.17. 
I am following this wiki https://github.com/Netflix/Priam/wiki/Setup 
where `CASS_HOME = /usr/share/cassandra`

when I try to run tomcat7 with priam added to webapps directory, i get 
`2016-01-14 22:29:56.0644 INFO localhost-startStop-1 com.netflix.priam.utils.TuneCassandra Fail writing cassandra.yaml file. Retry again!`

It keeps trying again and again resulting in 100% cpu usage.
Can you point out potential sources of error which might be causing this. I tried adding `LOGGER.info(e.getStackTrace().toString())` 
where this error is caught. But I get no stacktrace in priam.log(the deployed webapp being priam). I only get the above error.

Thanks

**Comment by pankajbhanu** [comment]
solved it by allowing others to write cassandra.yaml file

**Comment by nothau** [comment]
I'm having this same issue, using priam-3.x branch on a debian install of cassandra 2.1.14.  

Does CASS_HOME need to point to the configuration directory (/etc/cassandra) or the where the jar files live (/usr/share/cassandra)?

I've tried both and chmod 666 on the cassandra.yaml file with the same error.  

priam.log - 2016-05-19 21:42:55.0363 INFO localhost-startStop-1 com.netflix.priam.utils.TuneCassandra Fail wrting cassandra.yml file. Retry again!

I don't have any groups named "others"

**Comment by nothau** [comment]
Figured it out, Priam's web app is looking for cassandra.yaml in /etc/cassandra/conf/

**Comment by pdehlke** [comment]
Man, a simple e.getMessage() would have helped a lot here...

**Comment by tulumvinh** [comment]
Please submit a pull request for the additional "info" logging you desire.

**Comment by pdehlke** [comment]
PR472
