### ISSUE TITLE
Priam failed to start Cassandra server

### ISSUE THREAD

**Issue by TaoXiao** [Netflix/Priam#457]
Hi all,

I was trying to deploy Netflix Priam on a DSE cluster of 5 AMI DSE instances. The DSE version is 2.1.13.1131 and the Cassandra version is 4.8.5-1. 

I followed the [Priam setup wiki](https://github.com/Netflix/Priam/wiki/Setup) to setup Priam on each instance.

1.  Build the code
      I switched to branch “2.x” — the wiki says “Priam 2.0 is written to run with C* 2.X and DSE 4.X.” — and executed `./gradlew build`.  The build was successful and I could see “priam-web-2.7.0-SNAPSHOT.war” and "priam-cass-extensions-2.7.0-SNAPSHOT.jar" were generated. 

2. Setup ASG (Auto Scaling Group)
     I created a single ASG named “ASG_CassCluster” and attached all DSE instances to that ASG, actually my cluster name will be inferred from my ASG name to fetch Priam properties. 

3. Provide Credentials 
     I created a file “/etc/awscredential.properties” where I provided AWS accessid and secretekey.

4. Create S3 Bucket and SimpleDB Domains
     I created a S3 bucket where my backup files will be stored. I created two domains “InstanceIdentity” and “PriamProperties” in SimpleDB. 

5. Configure properties
     To change the default Priam propeties, I created the following property items in “PriamProperties” domain:

	|appId|property|value|
	|----|----|----|
	|ASG_CassCluster|priam.clustername|dseCassandraCluster|
	|ASG_CassCluster|priam.cass.home|/usr/share/dse/cassandra|
	|ASG_CassCluster|priam.cass.startscript|/etc/init.d/dse start|
	|ASG_CassCluster|priam.cass.stopscript|/etc/init.d/dse stop|
	|ASG_CassCluster|priam.yamlLocation|/etc/dse/cassandra/cassandra.yaml|
	|ASG_CassCluster|priam.data.location|/data/cassandra/data|
	|ASG_CassCluster|priam.cache.location|/data/cassandra/saved_caches|
	|ASG_CassCluster|priam.commitlog.location|/data/cassandra/commitlog|
	|ASG_CassCluster|priam.s3.bucket|my-cassandra-archive|

6.  Setup Web Container
      I downloaded Apache Tomcat 8.0.33 and put the generated “priam-web-2.7.0-SNAPSHOT.war”  into Tomcat’s “webapps” folder. 

7.  Deploy Priam Jar
      I put the generated “priam-cass-extensions-2.7.0-SNAPSHOT.jar” into Cassandra’s lib directory “/usr/share/dse/cassandra/lib”. Also I added “-javaagent:$CASS_HOME/lib/priam-cass-extensions-2.7.0-SNAPSHOT.jar” to Cassandra’s JVM argumens in the file “/etc/dse/cassandra/cassandra-env.sh” . 

Cassandra was already shutdown before I started Tomcat. 

After all the steps above were done, I started Tomcat by the command `sudo tomcat/bin/startup.sh`.   From [tomcat’s log](http://7xns6c.com1.z0.glb.clouddn.com/catalina.out.txt), I can see that all property items were fetched correctly from SimpleDB “PriamProperties” domain, including ASG name, appId, start/stop script, data directory, commitlog directory, etc. All the 5 instances in the ASG were also found.

But when Tomcat tried to start Cassandra server,  it threw the following exception:
```
INFO 15:59:27,540 No restore needed, task not scheduled
INFO 15:59:27,540 Starting cassandra server ....Join ring=true
INFO 15:59:27,541 Start cmd: [/etc/init.d/dse, start]
INFO 15:59:27,541 Start env: {TERM=xterm-256color, XFILESEARCHPATH=/usr/dt/app-defaults/%L/Dt, COMMIT_LOG_DIR=/data/cassandra/commitlog, SUDO_UID=1000, cassandra.join_ring=true, JMX_PORT=7199, MAIL=/var/mail/root, PWD=/home/ubuntu/tao, LOGNAME=root, SUDO_USER=ubuntu, NLSPATH=/usr/dt/lib/nls/msg/%L/%N.cat, SHELL=/bin/bash, LC_CTYPE=UTF-8, DATA_DIR=/data/cassandra/data, CACHE_DIR=/data/cassandra/saved_caches, SUDO_GID=1000, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, MAX_DIRECT_MEMORY=50G, HEAP_NEWSIZE=2G, USER=root, HOME=/home/ubuntu, LOCAL_BACKUP_DIR=mdo-backup, USERNAME=root, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:, SUDO_COMMAND=Tomcat/apache-tomcat-8.0.33/bin/startup.sh, MAX_HEAP_SIZE=8G, LANG=en_US.UTF-8}
INFO 15:59:27,544 Starting cassandra server ....
WARN 15:59:32,546 Starting Cassandra has an error
java.lang.IllegalThreadStateException: process hasn't exited
	at java.lang.UNIXProcess.exitValue(UNIXProcess.java:217)
	at com.netflix.priam.defaultimpl.CassandraProcessManager.start(CassandraProcessManager.java:77)
	at com.netflix.priam.PriamServer.intialize(PriamServer.java:138)
	at com.netflix.priam.defaultimpl.InjectedWebListener.getInjector(InjectedWebListener.java:51)
	at com.google.inject.servlet.GuiceServletContextListener.contextInitialized(GuiceServletContextListener.java:45)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4811)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5251)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```

Priam failed to start the Cassandra server. 

Does any body have similar problem ? Thanks.

**Comment by tulumvinh** [comment]
Hello,

The exception you provided is not fatal, most likely not the cause of your Cassandra process not starting.  

Try the following:
- Initiate a start of Cassandra.  On a node, execute the following curl cmd:  curl -v "http://localhost:8080/Priam/REST/v1/cassadmin/start"
- DSE Cassandra provides a log file of its start, it should be in the same directory as your other Cassandra logs.  An example of the start log file is:  dse_start-timestamp.out
- Review the start log to determine why the Cassandra process did not start.
- Also, if it exist, review the normal (system.log) Cassandra log file as well.

Regards

**Comment by TaoXiao** [comment]
Hi tulumvinh,

Thank you for you reply. I followed your suggestion but yet can't find the cause.

1. When I started tomcat and sent a http request “http://localhost:8080/Priam/REST/v1/cassadmin/start”, I got an error of “The requested resource is not available.” So it’s obvious Priam failed to start . But I can see that Tomcat container is running by executing the command “ps -ef | grep tomcat”

2. Cassandra’s log files (_output.log_ & _system.log_) were created but nothing was in them (I removed those log files before starting Tomcat to truncate early logs)  which indicates Cassandra got a starting command but failed to output anything to the log files — maybe Cassandra was indeed started but immediately crashed before it can produce anything to log file. 

In tomcat's log file (_catalina.out_), after it logs "Starting Cassandra has an error, java.lang.IllegalThreadStateException: process hasn't exited", it keeps logging many lines about filter:
```
 WARN 01:17:20,548 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/sdge_base/meter_missing-1a59e611e68b11e5832261f7932a86ce/backups, keyspace dir: sdge_base, CF: meter_missing-1a59e611e68b11e5832261f7932a86ce
 WARN 01:17:20,548 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/sdge_base/meter_list-1944a581e68b11e5832261f7932a86ce/backups, keyspace dir: sdge_base, CF: meter_list-1944a581e68b11e5832261f7932a86ce
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/sdge_base/meteraccount_list2-1ae62081e68b11e5832261f7932a86ce/backups, keyspace dir: sdge_base, CF: meteraccount_list2-1ae62081e68b11e5832261f7932a86ce
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/sdge_base/meter_reading-1c1810d1e68b11e5832261f7932a86ce/backups, keyspace dir: sdge_base, CF: meter_reading-1c1810d1e68b11e5832261f7932a86ce
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/sdge_base/loading_report-19b03891e68b11e5832261f7932a86ce/backups, keyspace dir: sdge_base, CF: loading_report-19b03891e68b11e5832261f7932a86ce
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/system_traces/sessions-c5e99f1686773914b17e960613512345/backups, keyspace dir: system_traces, CF: sessions-c5e99f1686773914b17e960613512345
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/backups, keyspace dir: system_traces, CF: events-8826e8e9e16a372887533bc1fc713c25
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/meter_reading-ceddc2b1b50211e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: meter_reading-ceddc2b1b50211e5bd181f78ff8a8d74
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/meter_write_test-60571721ba9211e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: meter_write_test-60571721ba9211e5bd181f78ff8a8d74
 WARN 01:17:20,549 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/meteraccount_list-cbf0b4e1b50211e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: meteraccount_list-cbf0b4e1b50211e5bd181f78ff8a8d74
 WARN 01:17:20,550 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/meter_list-c85cb8b1b50211e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: meter_list-c85cb8b1b50211e5bd181f78ff8a8d74
 WARN 01:17:20,550 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/loading_report-cd205b41b50211e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: loading_report-cd205b41b50211e5bd181f78ff8a8d74
 WARN 01:17:20,550 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/account_balance_update1-82558d11c80311e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: account_balance_update1-82558d11c80311e5bd181f78ff8a8d74
 WARN 01:17:20,550 Not a valid backup dir or keyspace/cf is part of the default filter.  SnapshotDir: /data/cassandra/data/smud_stage/accountbillinglog1-3d555dd1c80311e5bd181f78ff8a8d74/backups, keyspace dir: smud_stage, CF: accountbillinglog1-3d555dd1c80311e5bd181f78ff8a8d74
...
``` 

So what does that mean ? Is it scanning backup directories?

Thank you. 

Bests

**Comment by tulumvinh** [comment]
Hello, 

Are you still having issues?

Lasty, the latest builds of Priam (2.x and 3.x) eliminates the verbose logging you mentioned.

**Comment by dolphy17** [comment]
Hi tulumvinh,
I'm trying the same scenario with DSE 4.6.11 and cassandra process is unable to start for me. There're 2 issues that I've encountered with the setup:
- with -javaagent:priam-cass-extensions I got "Exception thrown by the agent : java.lang.NullPointerException" error with 'ps' command
- with -javaagent:priam-dse-extensions I got "Failed to find Premain-Class manifest attribute" error message in Cassandra output.log
- without any agent I got the following configuration error:
ERROR 13:23:38,100 Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: The hsha rpc_server_type is not compatible with an rpc_max_threads setting of 'unlimited'.  Please see the comments in cassandra.yaml for rpc_server_type and rpc_max_threads.

Any ideas?

**Comment by dolphy17** [comment]
I've managed to start the cluster with Priam:
- it's important to rename Priam-<version>-SNAPSHOT.war file to Priam.war before deploying it, otherwise Priam cannot find the endpoint,
- I switched to Apache Cassandra 2.0.8, because 2.x branch doesn't seem to be compatible with DSE versions (tried pure cassandra 2.0.17 and DSE 4.6), java agent crashes in Cassandra startup
