### ISSUE TITLE
No setup instructions for running outside of AWS

### ISSUE THREAD

**Issue by jmwri** [Netflix/Priam#463]
It would be very useful if there were some basic setup instructions that didn't rely on AWS.
I am running on my own hardware and can't really make sense of the setup.

**Comment by mohndoss** [comment]
Could you please some basic set-up instruction for my own cluster

**Comment by pdehlke** [comment]
Priam uses AWS intrinsics extensively; 'running outside of AWS' doesn't make much sense to Priam. It _might_ be possible to get it to work on an AWS-like infrastructure such as Eucalyptus, but I've never heard of anyone having even tried.
