### ISSUE TITLE
Issue with seeding

### ISSUE THREAD

**Issue by apurvasingh** [Netflix/Priam#469]
How am I meant to seed the first cassandra/priam node in my cluster? My first node fails to start, apparently because it's unable to find a list of seed(s).

What appears to be happening is that the NFSeedProvider is making REST calls to get a list of seed nodes and it is failing. Thus preventing Cassandra from completing the startup (because the Priam agent loops until that REST call succeeds).

Am I missing a step here where I might be required to bootstrap a node manually, without Priam, one that can be the seed node?

**Comment by tulumvinh** [comment]
Hi Apurva,

Overall, Priam's algorithm should recognize and select the first node as the "seed".  The algorithm is base within InstanceIdentity.getSeeds().  Unfortunately, this is not a common task so I will need for you to do the following to better understand your situation.

 Within InstanceIdentify, what is the size of the "locMap".  It should your initial node.  To best way to find this is to use "jdb" to enable interactive debugging on the node.  If you are not familiar with this, I can provide detail instructions.

Regards

**Comment by yashk** [comment]
@tulumvinh i am facing same issue while spinning up multi-region cassandra, can please you share instructions to use jdb

**Comment by tulumvinh** [comment]
@yashk please sync with Apurva as I believe he as a cluster bootstrapped.

As for jdb:
- Update Tomcat's setenv.sh, normally under /apps/tomcat/bin.  Set JVM argument "suspend" to "y".
- Restart Tomcat.  Tomcat will wait until jdb is attached.
- jdb -attach port (the port can be derived from the Tomcat log).

**Comment by tulumvinh** [comment]
Closing as original issue was with apurvasingh which he resolved.
