### ISSUE TITLE
Uneven distribution

### ISSUE THREAD

**Issue by ksangha** [Netflix/Priam#483]
Our 6 nodes have uneven distribution of data. The tokens are correctly set. Any reason why this would happen??
# 

Replicas: 3

Address      Rack        Status State   Load            Owns                Token  
                                                                            0113427455640312821154458202479064646084  
10.0.53.152  1d          Up     Normal  132.14 GB       85.47%              56713727820156410577229101240436610842  
10.0.52.241  1b          Up     Normal  25.91 GB        85.91%              28356863910078205288614550621122593221  
10.0.53.18   1d          Up     Normal  168.9 GB        14.53%              0141784319550391026443072753098378663705  
10.0.51.218  1a          Up     Normal  260.81 GB       55.14%              1808575600  
10.0.51.28   1a          Up     Normal  131.27 GB       44.86%              85070591730234615865843651859750628463  
10.0.52.54   1b          Up     Normal  160.63 GB       14.09%              0113427455640312821154458202479064646084

**Comment by tulumvinh** [comment]
What version of C* are you running?
Is this a new cluster?
If this is an existing cluster, are you sure the data pattern have not changed?

**Comment by ksangha** [comment]
C* 1.2
No. Existing cluster of 3 nodes was expanded to 6.

**Comment by tulumvinh** [comment]
Is this still an issue for your site?

**Comment by ksangha** [comment]
yes.

**Comment by vinaykumarchella** [comment]
@ksangha Did you run cleanup after doubling the cluster? If not running the clean up would clear the extra data from nodes.

**Comment by vinaykumarchella** [comment]
I closing this ticket considering it is the cleanup issue, if that is not the case, please open the tickets with `nodetool info` from all of the nodes.
