### ISSUE TITLE
Priam 2.x is unable to run Apache Cassandra 2.0.17

### ISSUE THREAD

**Issue by dolphy17** [Netflix/Priam#487]
Hi,

I got the following error message when Priam is trying to start Cassandra:

`ERROR 13:43:21,820 Fatal configuration error
org.apache.cassandra.exceptions.ConfigurationException: The hsha rpc_server_type is not compatible with an rpc_max_threads setting of 'unlimited'.  Please see the comments in cassandra.yaml for rpc_server_type and rpc_max_threads.
        at org.apache.cassandra.config.DatabaseDescriptor.applyConfig(DatabaseDescriptor.java:339)
        at org.apache.cassandra.config.DatabaseDescriptor.<clinit>(DatabaseDescriptor.java:112)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:213)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:554)
        at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:643)
The hsha rpc_server_type is not compatible with an rpc_max_threads setting of 'unlimited'.  Please see the comments in cassandra.yaml for rpc_server_type and rpc_max_threads.
Fatal configuration error; unable to start. See log for stacktrace.`

Using latest version of 2.x branch.

Please advise.

Regards,
Andor

**Comment by dolphy17** [comment]
Opened the following pull request:

https://github.com/Netflix/Priam/pull/491

**Comment by tulumvinh** [comment]
Hi Andor, pull request #491 looks good, just one question, are these yaml parameters applicable to C* 2.1 as well?

**Comment by dolphy17** [comment]
Yes, they are. The following has been copied from cassandra.yaml in 2.1.14 release:

```yaml
# Uncomment rpc_min|max_thread to set request pool size limits.
#
# Regardless of your choice of RPC server (see above), the number of maximum requests in the
# RPC thread pool dictates how many concurrent requests are possible (but if you are using the sync
# RPC server, it also dictates the number of clients that can be connected at all).
#
# The default is unlimited and thus provides no protection against clients overwhelming the server. You are
# encouraged to set a maximum that makes sense for you in production, but do keep in mind that
# rpc_max_threads represents the maximum number of client requests this server may execute concurrently.
#
# rpc_min_threads: 16
# rpc_max_threads: 2048
```
