### ISSUE TITLE
VPC, vnode support status?

### ISSUE THREAD

**Issue by dolphy17** [Netflix/Priam#496]
Hi,

What's the latest with running Priam in private VPC and virtual nodes?
I've found various issues regarding this, but can't really tell for sure.

Thanks,
Andor

**Comment by tulumvinh** [comment]
Hi Andor,

Branch 3.x has code that accounts for the following concerning VPC.  As for virtual nodes, there is no support at the moment.  However, if you would like to enhance to support this feature, we'll be glad to take a look at your pull request.

VPC features:
- For a node, determine if it is running in classic or vpc.  The use case is when a cluster is in hybrid mode (classic and vpc), each node will be aware of the AWS account/env it is running under.
- Update of AWS security group for nodes within vpc.

Regards

**Comment by dolphy17** [comment]
Thanks Vinh.
Do you recommend using the 3.x branch for Cassandra 2.0/2.1 deployments instead of 2.x?

**Comment by tulumvinh** [comment]
No, I would not due to 3.x eliminating non-applicable cassandra yaml entries, which still applies to Cassandra 2.0.

A better approach is to merge the vpc changes from branch 3.x to 2.x.  Do you want to give it a try?  Create a pull request and I'll review,

**Comment by dolphy17** [comment]
Sure, I can take a look next week.
So, basically 2.x branch is strictly for Cassandra 2.0 and 3.x is for 2.1.

**Comment by tulumvinh** [comment]
Yes.  In the near future, I am going to make Priam, 3.x branch compatible with Cassandra 2.0 as well.  This eliminates the need to support two branches.
