### ISSUE TITLE
Is commitlog backup stable already?

### ISSUE THREAD

**Issue by dolphy17** [Netflix/Priam#521]
Hi,

Can I use commitlog backup in production?
I tried it and it crashed on 2.x branch, but did't have a chance to try it with 3.x.

Anybody using it already?

Thanks,
Andor

**Comment by tulumvinh** [comment]
Send me the stack trace of the crash.

3.x and 2.x should be the same in terms of this feature.

**Comment by tulumvinh** [comment]
This issue seems to be related / resolve by pr #552
