### ISSUE TITLE
Is autoscaling required for Priam?

### ISSUE THREAD

**Issue by ysgard** [Netflix/Priam#560]
We have an existing cluster in AWS that isn't in an autoscaling group.  Can we still use Priam?  It seems that we should be able to, but there's this:

`NOTE: Your cluster name is inferred from your ASG name to fetch Priam properties.`

**Comment by arunagrawal84** [comment]
@ysgard Priam assumes that your cluster is behind autoscaling group to ensure that new instances come up and priam can grab the dead token and start Cassandra automatically.

**Comment by arunagrawal84** [comment]
Closing this as we have bigger discussion going on #589
