### ISSUE TITLE
more of a question than issue regarding C 3.11 and vnodes

### ISSUE THREAD

**Issue by DoctorOgg** [Netflix/Priam#577]
ok, so i have a small cluster, however from the reading it seems priam is not ready for 3.11 using vnodes, is this true? and if so any idea when it will be supported?

Thanks!

**Comment by arunagrawal84** [comment]
We are currently working on 3.11 branch for Priam. I am shooting for somewhere about mid-August.

**Comment by DoctorOgg** [comment]
thanks!
