### ISSUE TITLE
SimpleDB Cost Estimate

### ISSUE THREAD

**Issue by cajnoj** [Netflix/Priam#581]
Before starting to use Priam, I'd like to have some idea about the expected SimpleDB-related usage costs.
Our initial cluster will have 6 nodes.

1. **SimpleDB Machine Utilization** - is it expected to remain under 25 hours? If not, how many hours is Priam expected to use?
2. **SimpleDB Data Transfer Out** - is it expected to remain under 1 GB? If not, what will the data consumption be?
3. **SimpleDB Structured Data Storage** - am I correct in assuming that the data size will not be above 1GB?

**Comment by arunagrawal84** [comment]
@cajnoj SimpleDB is used only for token management in Priam. Note that it is not required and you can manage token yourself using configuration files as well. Simple DB allows auto bootstrap of instances if you loose them. 
Priam token management is done at every (re)start of Priam and every 2 minutes to manage security group ingress. During this call, it goes and finds all the tokens for this cluster (or create new).

I am assuming you meant 25 hours/month. With that cluster size, I would expect very low usage of SimpleDB. I would not expect more than few MB consumption and few KB's of data in simple DB. If at all, traffic becomes too much, then if this is a single region cluster, you may want to disable UpdateSecuritySettings, so you only contact at (re)start of Priam for token management. Note UpdateSecuritySettings is meant for cross-region communication.
