### ISSUE TITLE
Can you please document how to take backup and restore it ?

### ISSUE THREAD

**Issue by ksachdeva11** [Netflix/Priam#582]
Presently there is no proper document listing steps to follow for setup and taking and restoring cassandra backup.

Can you please list down the steps ?

Thanks!

**Comment by arunagrawal84** [comment]
@ksachdeva11 Backup and restore functionality is supported natively on Priam. What it translates to is for taking the backup you need to update the configurations (there are multiple for backup to tweak as per your needs) and Priam will start the backup and store them on S3. Same goes for restore where you point it to the S3 bucket and date range, and it will start in restore mode. To see the properties refer to https://github.com/Netflix/Priam/wiki/Cluster-Management. 
To invoke manual backups/restore, please consult https://github.com/Netflix/Priam/wiki/REST-API
Let me know if you think this documentation does not suffice as there is always room to improve.

**Comment by arunagrawal84** [comment]
@ksachdeva11 Did those articles help you in finding how to do backup and restore?

**Comment by arunagrawal84** [comment]
Closing this request.
