### ISSUE TITLE
Priam is writing lots of debug logs to catalina.out

### ISSUE THREAD

**Issue by NickBlow** [Netflix/Priam#597]
We are trying to set up Priam using the 3.11 branch in Tomcat. It's all working fine, but we are having issues with logs. We're struggling to get Priam to pick up the log4j properties, and it's just logging huge amounts of debug info to catalina.out.

Our log4j config is the following (priam_log_file is injected via ansible). We are putting it in priam/src/main/resources/log4j.properties, then building with the provided gradle script. We also tried to put it into priam-web/src/main/resources/log4j.properties and had the same issue. I'm sure we're missing something obvious, but we're struggling to see it.

```log4j.debug=FALSE
log4j.rootLogger=ERROR, FILE, stdout
log4j.appender.FILE=org.apache.log4j.RollingFileAppender
log4j.appender.FILE.File={{priam_log_file}}
log4j.appender.FILE.MaxFileSize=5MB
log4j.appender.FILE.MaxBackupIndex=5
log4j.appender.FILE.layout=org.apache.log4j.PatternLayout
log4j.appender.FILE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSSS} %p %t %c %m%n
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p %d{HH:mm:ss,SSS} %m%n
```

**Comment by zmarois** [comment]
@NickBlow dunno if you figured out what was causing this, but I think it was multiple slf4j bindings on the classpath. I believe https://github.com/Netflix/Priam/pull/631 and https://github.com/Netflix/Priam/pull/632 fix this.

**Comment by NickBlow** [comment]
@zmarois we ended up using filebeat to work around it rather than actually trying to dig deep into what was causing it. that sounds plausible. will close now and reopen should it not be fixed by those.
