### ISSUE TITLE
What is the version of Priam to install on AWS for Cassandra 3.9?

### ISSUE THREAD

**Issue by amr46** [Netflix/Priam#606]
The most recent version of cassandra installed via datastax's repo on AWS CentOS is Cassandra 3.9

However, looking at the [compatibility](https://github.com/Netflix/Priam/wiki/Compatibility
) page, there does not appear to be a version of Priam compatible with Cassandra 3.9. 

What are the suggested versions of Cassandra/Priam to install in this case?

Thanks in advance.

**Comment by arunagrawal84** [comment]
@amr46 3.x branch of Priam should be reasonably compatible with C* 3.9. That being said, I cannot say it will work for sure as I have not tested personally. But that is where I would put my money. 

Also, current branch of `3.11` may work but I plan to upgrade the dependency `org.apache.cassandra:cassandra-all:2.1.17` to `org.apache.cassandra:cassandra-all:3.11` which may break 3.9 in future(depending what has changed) if you use that branch.  

Note that in Netflix, we are moving to Apache Cassandra 3.11 as we found that to be more stable.

**Comment by amr46** [comment]
Thanks for the info. 
Would you say then that Priam 3.11 will play well with Cassandra 3.11, or is that still to be thoroughly vetted?

**Comment by amr46** [comment]
Also, what's the most recent and stable priam/cassandra version combo that you suggest using?
Thanks in advance @arunagrawal84 .

**Comment by arunagrawal84** [comment]
@amr46 Yes, 3.11 should play well with 3.11 Apache Cassandra. We are currently running Apache C* and Priam 3.11 in the TEST environment. We have not found any issues yet with that combination. 
* Note we have not yet tested with 3.11.1 (which released today 10/10/2017)

**Comment by amr46** [comment]
I'll go with 3.11 in both cases then. Thanks!
