### ISSUE TITLE
3.11 - PriamConfiguration fails to run correctly on a single AWS EC2 instance in a VPC

### ISSUE THREAD

**Issue by amr46** [Netflix/Priam#607]
During startup, an exception is thrown that results in the PriamServer not being initialized correctly. 

I'm running on an m4 EC2 instance in a VPC. This has only local hostnames and ips. No public hostnames or IPs. I've configured the EC2 to have access to S3 and SimpleDB via an IAM role. 
Cassandra version: 3.11

- [InjectedWebListener](https://github.com/Netflix/Priam/blob/3.11/priam/src/main/java/com/netflix/priam/defaultimpl/InjectedWebListener.java#L47) creates an instance of PriamConfiguration and calls intialize() on it

- [PriamConfiguration intialize()](https://github.com/Netflix/Priam/blob/3.11/priam/src/main/java/com/netflix/priam/defaultimpl/PriamConfiguration.java#L290) gets invoked causing this line to throw an exception on an amazon EC2 instance running in a VPC (with no public hostname or public IP), resulting in the rest of initialization failing (no REST endpoints exposed by the webserver etc. eg. get_token will return a 404). The LOCAL_HOSTNAME and LOCAL_IP in this file don't seem to get used anywhere either and look private. 

- Once the above issue is mitigated by adding try/catch blocks around the offending calls on intialize(), the priam server starts up correctly and get_token returns the simpledb token. 

- Further, most if not all the logic for getting Seed nodes relies on the seed ec2 instance's public hostname translation into IPs - public hostnames don't exist for nodes in a VPC. To elaborate: [NFSeedProvider](https://github.com/Netflix/Priam/blob/3.11/priam/src/main/java/com/netflix/priam/defaultimpl/PriamConfiguration.java#L290) calls "http://127.0.0.1:8080/Priam/REST/v1/cassconfig/get_seeds" 
 ->[ priamServer.getId().getSeeds()](https://github.com/Netflix/Priam/blob/3.11/priam/src/main/java/com/netflix/priam/identity/InstanceIdentity.java#L276) -> [PriamInstance.getHostName()](https://github.com/Netflix/Priam/blob/3.11/priam/src/main/java/com/netflix/priam/identity/PriamInstance.java#L75) for a single DC -> returns public Hostname. 

I wanted to understand if I'm doing something wrong in multiple places re: hostnames in vpcs, or whether Priam isn't fully fleshed out to work in a VPC yet.

**Comment by arunagrawal84** [comment]
@amr46 Netflix entire fleet of Cassandra is in VPC. Since we are hosted in multiple datacenters/regions, we always host with instances where public IP/hostname. Public IP is required to create a global ring so instances from different regions can communicate with each other. My recommendation would be to host with instances where you have public IP so you may "expand" your cluster in other regions (if that is not already the case).

**Comment by amr46** [comment]
Okay, to just clarify what you said - 
- You host Cassandra in multiple regions. 
- Each region has it's own VPC and the nodes where you're running Priam all have public IPs and hostnames. 
- Cross regional communication happens by listing these region-specific seed node IPs in your various cassandra.yaml files for seed-node discoverability. 

Could you confirm the above? Then feel free to close the issue.

PS: it's highly informative to see how a huge company like Netflix plans its architecture to scale out availability. Thanks again for all your feedback.

**Comment by arunagrawal84** [comment]
@amr46 Yes, we host Cassandra in 3 regions for availability. Within each region, we host in 3 availability zones. 
Yes, we only host in VPC where we have public IP/hostname. 
We don't put EC2 instance list in cassandra.yaml as EC2 instances may die. Instead, we make a callback to Priam who takes care of publishing the current list of EC2 instances via querying Amazon via NFSeedProvider.

**Comment by amr46** [comment]
got it. Please feel free to close this
