### ISSUE TITLE
Does 3.11 branch not use vnodes?

### ISSUE THREAD

**Issue by darkpssngr** [Netflix/Priam#610]
The readme says priam uses simpleDB to manage tokens. But then I don't see simpleDB anymore in the AWS console. So, I'm not sure if it still uses it. clarity on this would help

Thanks

**Comment by arunagrawal84** [comment]
@darkpssngr Priam does not have good support of `vnodes` irrespective of the branch. Netflix has always hosted one token per EC2 instance. 

Regarding simpleDB offering from Amazon, I would let you contact Amazon for that. With some research, I found pricing for SimpleDB: https://aws.amazon.com/simpledb/pricing/ so I would assume it is still being offered.

Priam uses either local file or SimpleDB for token management and is fully supported. The interface allows you to have a custom binding for any database of your choice as well (RDS/DynamoDB etc). Inside Netflix, we use another Cassandra cluster to manage tokens. I will be working on making that binding open source next year.  If you end up writing a custom interface for other DB offerings (irrespective of cloud provider), please feel free to submit a pull request as I am sure others can benefit too.

**Comment by jacktasia** [comment]
@darkpssngr  FWIW, AWS just does not have a console UI for SimpleDB. This was confusing for me too at first. You must use their API. Assuming you're using aws-cli these commands may be helpful:

`aws sdb create-domain --domain-name InstanceIdentity`
`aws sdb create-domain --domain-name PriamProperties`

`aws sdb select --select-expression 'SELECT * FROM InstanceIdentity'`

**Comment by darkpssngr** [comment]
@arunagrawal84  @jacktasia: Got it thanks :)
