### ISSUE TITLE
Error building cassandra 3.11

### ISSUE THREAD

**Issue by amr46** [Netflix/Priam#633]
./gradlew build

> Configure project :
Inferred project: priam, version: 3.12.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint
> java.lang.NoClassDefFoundError: nebula/plugin/dependencylock/DependencyLockPlugin$LockVersionConstaint

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s

This wasn't happening just a few weeks ago. 
528b22a8802afb641436e276b454ea66dc5821d4 is the sha I'm using. 

Help appreciated. 

Thanks.

**Comment by arunagrawal84** [comment]
@amr46 This was due to the fact that gradle 4 and netlifxoss did not play well. Updated to latest gradle 4.4 and netflixoss. If you pull latest code it should work.

**Comment by amr46** [comment]
Testing it now - it was also broken in master FYI.

**Comment by arunagrawal84** [comment]
@amr46 Yes, master is not going to build as is. There are multiple things which are wrong in `master` branch and as it stands it is more or less deprecated because I hardly know folks who are still using C* 1.x. We plan to merge `3.x` to `master` but it is not high on priority list. 
fyi: 3.x (C* 2.x and 3.0.x) and 3.11 (C* 3.11) are branches where major development work is going on.

**Comment by vuminh88** [comment]
can you guys give us a workaround to build?
I tried several tags but still failed to build.

**Comment by arunagrawal84** [comment]
@vuminh88 @amr46 does it work for you now? Ensure that you have done a rebase of your 3.x and/or 3.11 branches to latest. 
master branch as it stands is deprecated. We need to do a full merge of 3.x to master. See #601

**Comment by arunagrawal84** [comment]
@amr46 @vuminh88 sandeepgajjam Fixed master so it will build now with fix: #648 
Ensure you rebase your master to latest and then do gradle build.
