### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by vuminh88** [Netflix/Priam#641]
Hi Team,
I'm trying to build Priam but seems like we have guava version issue.
**This my java version:**
$ java -version
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

**And this is my build log:**
$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)
Inferred project: Priam, version: 3.12.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: org/gradle/api/artifacts/VersionConstraint
> java.lang.NoClassDefFoundError: org/gradle/api/artifacts/VersionConstraint

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Please help me to investigate this.

**Comment by zmarois** [comment]
I've also been having this issue for the past week or so. A workaround for me for the time-being is to comment out the "nebula.netflixoss" plugin, or change it to version 4.0.0.

Version 5.0.0 (as well as the old version 3.6.4) seems to be corrupt.

**Comment by zmarois** [comment]
This also hasn't seemed to be a problem on the travis CI runner. I don't have any good reason for this, just the data point.

**Comment by arunagrawal84** [comment]
@zmarois @vuminh88 can you confirm if your local file gradle/wrapper/gradle-wrapper.properties show gradle-4.4-bin.zip
If that is not the case, you may manually move it to 4.4 if it is stuck on 4.0

**Comment by zmarois** [comment]
Yup, that fixed it for me. Just need to rebase my branches. Thanks

**Comment by vuminh88** [comment]
I tried your way (ie change gradle/wrapper/gradle-wrapper.properties to gradle 4.4, in master branch it is 3.1) but it didn't work.
Any other idea?

**Comment by vuminh88** [comment]
It worked for how. What I've done is:
- Checkout branch 3.x
- run  ./gradlew build -x test
