### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by sandeepgajjam** [Netflix/Priam#645]
> Configure project : 
Inferred project: Priam, version: 3.12.0-SNAPSHOT

> Configure project :priam 
The testJar task is deprecated.  Please place common test harness code in its own project and publish separately.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/ubuntu/Priam/priam-web/build.gradle' line: 2

* What went wrong:
Plugin [id: 'jetty'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/4.4/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (plugin dependency must include a version number for this source)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by arunagrawal84** [comment]
@sandeepgajjam Please see #641 and #633

**Comment by arunagrawal84** [comment]
Please reopen if there is still an issue.
