### ISSUE TITLE
Unable to build on Ubuntu 12.04/OpenJDK

### ISSUE THREAD

**Issue by jbiel** [Netflix/Priam#71]
Hello,

I'm attempting to build the master branch using Ubuntu 12.04 x64/OpenJDK7 and I'm receiving a NullPointerException. I've tried OpenJDK6 as well and gotten the same error. Can anyone point me in the right direction?

Thanks

Full debug trace here:
http://filebin.ca/GNWqW8GXWAv/output.txt

16:13:59.468 [ERROR] [org.gradle.BuildExceptionReporter] > java.lang.NullPointerException (no error message)
# java -version

java version "1.7.0_07"
OpenJDK Runtime Environment (IcedTea7 2.3.2) (7u7-2.3.2-1ubuntu0.12.04.1)
OpenJDK 64-Bit Server VM (build 23.2-b09, mixed mode)

**Comment by sihaizhida** [comment]
Hello,everyone！
I’m trying to run Priam under Ubuntu14.04, but I'm not familiar with the AWS environment setup, could anyone tell how to do that? Thank you!
